export const REGISTER_USER = "REGISTER_USER"
export const REQUEST_NUMBERPHONE = "REQUEST_NUMBERPHONE"
export const REQUEST_VERIFYCODE = "REQUEST_VERIFYCODE"
export const DATA_STEPS_REGISTER = "DATA_STEPS_REGISTER"